### ISSUE TITLE
type MulticlassLDA has no field projw

### ISSUE THREAD

**Issue by adinhobl** [JuliaAI/MLJMultivariateStatsInterface.jl#12]
My apologies for opening a new issue so soon. I'm trying to run a Multivariate LDA through MLJ using the MultivariateStats package. I've run into an issue where running a transform after fitting the model errors out.

![image](https://user-images.githubusercontent.com/29109741/97133356-cb741080-1717-11eb-950c-270109773e8e.png)

I've tried restarting the notebook kernel a few times, but this keeps coming up. The specific line it appears to error on is [here](https://github.com/alan-turing-institute/MLJMultivariateStatsInterface.jl/blob/0b996da48eeb111c95dcc7e1a375a646c4e1d900/src/models/discriminant_analysis.jl#L291 ). I'm not sure where the `core_res.projw` object comes from. There's another LDA method that refers to `core_res.proj` only.

I also tried SubspaceLDA, which works without error and also has a method with `projw`. I just swapped added "Subspace" to the code above to do this, no other changes.

I'm not sure if I'm doing something wrong or causing it to dispatch incorrectly.

**Comment by tlienart** [comment]
Hmm, @OkonSamuel would you mind taking a look? thanks!

**Comment by OkonSamuel** [comment]
I'll fix this today

**Comment by adinhobl** [comment]
Can confirm that after updating and re-running that it works. Thanks!
