### ISSUE TITLE
Documentation tracking issue

### ISSUE THREAD

**Issue by josephsdavid** [JuliaAI/MLJMultivariateStatsInterface.jl#38]
TODO:
- [ ] LinearRegressor,
- [ ] MultitargetLinearRegressor,
- [ ] RidgeRegressor,
- [ ] MultitargetRidgeRegressor,
- [ ] PCA,
- [ ] KernelPCA,
- [ ] ICA,
- [ ] LDA,
- [ ] BayesianLDA,
- [ ] SubspaceLDA,
- [ ] BayesianSubspaceLDA,
- [ ] FactorAnalysis,
- [ ] PPCA
- [ ] code review!

**Comment by ablaom** [comment]
closed as completed
