### ISSUE TITLE
How to access loadings() or reconstruct()?

### ISSUE THREAD

**Issue by WilliamZimmerman83** [JuliaAI/MLJMultivariateStatsInterface.jl#53]
Hi,

How do you get reconstruct or loadings to work with your package? 

```
## PCA model
PCA = @iload PCA pkg="MultivariateStats"
mach = machine(PCA(), cluster_df[:, Not([:organisation_srg_key, :customer_bucket])])
fit!(mach)

# compute explained variance for each dimension
report(mach).principalvars
report(mach).mean
```

For MultivariateStats the code would be: 

```
M = fit(PCA, cluster_m)
loadings(M)
```

Cheers,

**Comment by OkonSamuel** [comment]
Hi @WilliamZimmerman83 
To get `reconstruct` just call `inverse_transform(mach, X)`
For loadings try doing `report(mach).loadings`

**Comment by WilliamZimmerman83** [comment]
report(mach) doesn't have a loadings fields:

`ERROR: type NamedTuple has no field loadings`

The only fields I have available in report are:
indim 
outdim 
tprincipalvar
tresidualvar
tvar
mean 
principalvars

It would be really nice to get the loadings and projection matrix (the same as PCA)

**Comment by OkonSamuel** [comment]
@WilliamZimmerman83 That seems like a bug. 
I'll open a PR to fix this

**Comment by OkonSamuel** [comment]
@WilliamZimmerman83 https://github.com/JuliaAI/MLJMultivariateStatsInterface.jl/releases/tag/v0.5.1
